version: '3.9'

services:
  postgres:
    image: postgres:15-alpine
    container_name: spiral_db
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=spiralMatrix
      - POSTGRES_PASSWORD=qwerty
