version: '3.9'

services:

  postgres:
    image: postgres:15-alpine
    container_name: spiral_db
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=spiralMatrix
      - POSTGRES_PASSWORD=qwerty
    networks: 
      - backend
  app:
    build:
      context: ../../
      dockerfile: deploy/db/Dockerfile 
    image: spiral_app
    container_name: spiral_app
    ports:
      - 8080:8080
    depends_on:
      - postgres
    networks:
      - backend
    env_file:
      - ../../.env

networks:
  backend:
