version: '3.9'

services:

  postgres:
    image: postgres:15-alpine
    container_name: spiral_db
    ports:
      - 5432:5432
    volumes:
      - /tmp/postgres:/var/lib/postgresql/data
    env_file:
      - ../../.env
    networks: 
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  app:
    build:
      context: ../../
      dockerfile: deploy/app/Dockerfile 
    image: spiral_app
    container_name: spiral_app
    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - backend
    env_file:
      - ../../.env

networks:
  backend:
